openapi: "3.0.0"
info:
  version: "0.3"
  title: "arXiv fulltext extraction service"
  contact:
    name: "arXiv API Team"
    email: nextgen@arxiv.org
  license:
    name: MIT

paths:
  /{paper_id}:
    get:
      operationId: getLatestExtraction
      summary: |
        Retrieve the latest extraction for a paper.
      responses:
        '200':
          description: |
            An extraction for the current version of the extractor exists.
          content:
            text/plain:
              schema:
                type: string
        '303':
          description: |
            An extraction task exists for this paper using the current
            extractor version.
          headers:
            Location:
              description: The URI of the extraction task.
              schema:
                type: string

    post:
      operationId: forceExtraction
      responses:
        '202':
          description: |
            An extraction task has been created for this paper using the
            current extractor version.
          headers:
            Location:
              description: The URI of the extraction task.
              schema:
                type: string
        '401':
          description: Unauthorized. Missing valid authentication information.
        '403':
          description: |
            Forbidden. Client or user is not authorized to force extraction.

  /{paper_id}/format/{format}:
    get:
      operationId: getLatestExtractionByFormat
      summary: |
        Retrieve an extraction for a paper in a specific format.
      responses:
        '200':
          description: The requested format exists.
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: The requested format does not exist.

  /{paper_id}/version/{extractor_version}:
    get:
      operationId: getExtractionByVersion
      summary: |
        Retrieve an extraction for a paper from a specific extractor
        version.
      responses:
        '200':
          description: The requested version exists.
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: The requested version does not exist.

  /{paper_id}/version/{extractor_version}/format/{format}:
    get:
      operationId: getExtractionByVersionAndFormat
      summary: |
        Retrieve an extraction for a paper from a specific extractor version
        in a specific format.
      responses:
        '200':
          description: The requested version and format exists.
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: The requested version + format does not exist.

  /submission/{submission_id}:
    get:
      operationId: getLatestSubmissionExtraction
      summary: |
        Retrieve the latest extraction for a submission.
      responses:
        '200':
          description: |
            An extraction for the current version of the extractor exists.
          content:
            text/plain:
              schema:
                type: string
        '303':
          description: |
            An extraction task exists for this submission using the current
            extractor version.
          headers:
            Location:
              description: The URI of the extraction task.
              schema:
                type: string

    post:
      operationId: ForceSubmissionExtraction
      responses:
        '202':
          description: |
            An extraction task has been created for this submission using the
            current extractor version.
          headers:
            Location:
              description: The URI of the extraction task.
              schema:
                type: string
        '401':
          description: Unauthorized. Missing valid authentication information.
        '403':
          description: |
            Forbidden. Client or user is not authorized to force extraction.

  /submission/{submission_id}/format/{format}:
    get:
      operationId: getSubmissionExtractionByFormat
      summary: |
        Retrieve an extraction for a submission in a specific format.
      responses:
        '200':
          description: The requested format exists.
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: The requested format does not exist.

  /submission/{submission_id}/version/{extractor_version}:
    get:
      operationId: getSubmissionExtractionByVersion
      summary: |
        Retrieve an extraction for a submission from a specific extractor
        version.
      responses:
        '200':
          description: The requested version exists.
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: The requested version does not exist.

  /submission/{submission_id}/version/{extractor_version}/format/{format}:
    get:
      operationId: getSubmissionExtractionByVersionAndFormat
      summary: |
        Retrieve an extraction for a submission from a specific extractor
        version in a specific format.
      responses:
        '200':
          description: The requested version and format exists.
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: The requested version + format does not exist.


  /status/{task_id}:
    get:
      operationId: getExtractionTaskStatus
      summary: |
        Get the current status of an extraction task. If the extraction task
        has completed successfully, redirects to the resulting fulltext
        resource.
      responses:
        '200':
          description: |
            The extraction task exists, and is either pending, running, or has
            failed.
          content:
            application/json:
              schema:
                $ref: 'resources/status.json'
        '303':
          description: |
            The extraction task has completed successfully, and a fulltext
            resource exists.
          headers:
            Location:
              description: |
                The URI of the fulltext resource created by this extraction
                task.
              schema:
                type: string
        '404':
          description: The requested task does not exist.
